# dependencies
markdown:         kramdown
highlighter:      pygments

# permalinks
permalink:        pretty
# relative_permalinks: true

# setup
title:            'B.F.G.'
tagline:          'online demesne'
description:      '<a class="siteDescriptionLink" href="https://bfgriffith.github.io/about/">personal internet demesne</a>,<br><a class="siteDescriptionLink" href="https://bfgriffith.github.io/Professional-Portfolio/">web-development</a> and<br><a class="siteDescriptionLink" href="https://bfgriffith.github.io/writing-portfolio/">creative-writing</a> portfolios,<br>and wide-ranging <a class="siteDescriptionLink" href="https://bfgriffith.github.io/blog-archive/">blog</a>'
url:              https://bfgriffith.github.io/
baseurl:          /

author:
  name:           'B.F. Griffith'
  url:            https://bfgriffith.github.io/

paginate:         1
paginate_path:    "/coding-blog/page:num/"

# custom variables
version:          1.1.1

github:           
  repo:           https://github.com/BFGriffith/BFGriffith.github.io
