# dependencies
markdown:         kramdown
highlighter:      pygments

# permalinks
permalink:        pretty
# relative_permalinks: true

# setup
title:            Ben Forbes Griffith
tagline:          'GitHub demesne'
description:      '<p><a href="https://bfgriffith.github.io/about/">web-development portfolio</a> and <a href="https://bfgriffith.github.io/">blog</a></p>'
url:              https://bfgriffith.github.io/
baseurl:          /

author:
  name:           'Ben Forbes Griffith'
  url:            https://bfgriffith.github.io/

paginate:         5

# custom variables
version:          1.0.0

github:
  repo:           https://github.com/BFGriffith/BFGriffith.github.io
