# dependencies
markdown:         kramdown
highlighter:      pygments

# permalinks
permalink:        pretty
# relative_permalinks: true

# setup
title:            'B.F.G.'
tagline:          'online demesne'
description:      '<a class="siteDescriptionLink" href="https://bfgriffith.github.io/about/">personal internet demesne</a>,<br><a class="siteDescriptionLink" href="https://bfgriffith.github.io/professional-portfolio/">web-development</a> and<br><a class="siteDescriptionLink" href="https://bfgriffith.github.io/writing-portfolio/">creative-writing</a> portfolios,<br>and <a class="siteDescriptionLink" href="https://bfgriffith.github.io/journals-archive/">public journals</a>'
url:              https://bfgriffith.github.io/
baseurl:          /

author:
  name:           'B.F. Griffith'
  url:            https://bfgriffith.github.io/

paginate:         1
paginate_path:    "/journal/page:num/"

# custom variables
version:          1.3

github:           
  repo:           https://github.com/BFGriffith/BFGriffith.github.io
